build:
    environment:
        php:
            version: 5.6.20
    dependencies:
        before:
            - sudo composer self-update && composer --version
            - composer global require "fxp/composer-asset-plugin:1.*"